<?xml version="1.0"?>
<robot name="mecanum_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Xacro parameters -->
    <xacro:property name="base_length" value="0.4"/>
    <xacro:property name="base_height" value="0.15"/>
    <xacro:property name="base_width" value="0.3"/>
    <xacro:property name="wheel_radius" value="0.05"/>
    <xacro:property name="wheel_length" value="0.03"/>
    <xacro:property name="rotate_90" value="1.57"/>
    <xacro:property name="l_b" value ="0.14"/>
    <xacro:property name="imu_length" value = "0.05"/>
    <xacro:property name="imu_height" value= "0.01"/>
    <xacro:property name="imu_width" value= "0.05"/>

    <!-- Wheel macro -->
    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <!-- Rotate cylinder to roll correctly along Y axis -->
                <origin xyz="0.0 0.0 0.0" rpy="${rotate_90} 0.0 0.0"/>
                <material name="red"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius}"/>
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            </collision>
            <xacro:cylinder_inertia 
                m="1.0" 
                r="${wheel_radius}" 
                l="${wheel_length}" 
                o_xyz="0.0 0.0 0.0" 
                o_rpy="0.0 ${rotate_90} 0.0"/>
        </link>
    </xacro:macro>

    <!-- Instantiate wheels -->
    <xacro:wheel_link prefix="front_right"/>
    <xacro:wheel_link prefix="front_left"/>
    <xacro:wheel_link prefix="back_right"/>
    <xacro:wheel_link prefix="back_left"/>

    <!-- Base links -->
    <link name="base_footprint"/>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${base_height / 2.0}" rpy="0.0 0.0 0.0"/>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${base_height / 2.0}" rpy="0.0 0.0 0.0"/>
        </collision>
        <xacro:box_inertia 
            m="5.0" 
            x="${base_length}" 
            y="${base_width}" 
            z="${base_height}" 
            o_xyz="0.0 0.0 ${base_height / 2.0}" 
            o_rpy="0.0 0.0 0.0"/>
    </link>

    <!-- IMU links -->
    <link name="imu_link">
        <visual>
            <geometry>
                <box size="${imu_length} ${imu_width} ${imu_height}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${imu_height/2}" rpy="0.0 0.0 0.0"/>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <box size="${imu_length} ${imu_width} ${imu_height}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${imu_height/2}" rpy="0.0 0.0 0.0"/>
        </collision>
        <xacro:box_inertia 
            m="0.09" 
            x="${imu_length}" 
            y="${imu_width}" 
            z="${imu_height}" 
            o_xyz="0.0 0.0 ${imu_height/2}" 
            o_rpy="0.0 0.0 0.0"/>
    </link>

    <!-- Joints -->
    <!-- base footprint base link joint-->
    <joint name="base_footprint_base_link_joint" type="fixed">
        <origin xyz="0.0 0.0 ${wheel_radius}" rpy="0.0 0.0 0.0"/>
        <parent link="base_footprint"/>
        <child link="base_link"/>
    </joint>

    <!-- base link and imu joint-->
    <joint name="base_link_imu_link_joint" type="fixed">
        <origin xyz="0.0 0.0 ${base_height}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="imu_link"/>
    </joint>

    <!-- front right wheel joint-->
    <joint name="base_front_right_wheel_joint" type="revolute">
        <origin xyz="${base_length/2 - (base_length/2- l_b)} ${-base_width/2 - wheel_length/2} 0.0" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="front_right_wheel_link"/>
        <axis xyz="0.0 1.0 0.0"/>
        <limit lower="0.0" upper="6.28" effort="100.0" velocity="5.0"/>
    </joint>

    <!-- front left wheel joint-->
    <joint name="base_front_left_wheel_joint" type="revolute">
        <origin xyz="${base_length/2 - (base_length/2- l_b)} ${base_width/2 + wheel_length/2} 0.0" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="front_left_wheel_link"/>
        <axis xyz="0.0 1.0 0.0"/>
        <limit lower="0.0" upper="6.28" effort="100.0" velocity="5.0"/>
    </joint>

    <!-- back right wheel joint-->
    <joint name="base_back_right_wheel_joint" type="revolute">
        <origin xyz="${-base_length/2 - (-base_length/2 + l_b)} ${-base_width/2 - wheel_length/2} 0.0" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="back_right_wheel_link"/>
        <axis xyz="0.0 1.0 0.0"/>
        <limit lower="0.0" upper="6.28" effort="100.0" velocity="5.0"/>
    </joint>

    <!-- back left wheel joint-->
    <joint name="base_back_left_wheel_joint" type="revolute">
        <origin xyz="${-base_length/2 - (-base_length/2 + l_b)} ${base_width/2 + wheel_length/2} 0.0" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="back_left_wheel_link"/>
        <axis xyz="0.0 1.0 0.0"/>
        <limit lower="0.0" upper="6.28" effort="100.0" velocity="5.0"/>
    </joint>

</robot>